### ISSUE TITLE
Pre-commit hooks only checks files in root of repo

### ISSUE THREAD

**Issue by joakimnordling** [twu/skjold#113]
The pattern for files in [.pre-commit-hooks.yaml](https://github.com/twu/skjold/blob/205cae90328a29fd98b8056f31b16d6ca11736df/.pre-commit-hooks.yaml#L9) are set up to only check any `poetry.lock`, `Pipfile.lock` and `requirements*.txt` files in the root of the repo. However it's not really uncommon that you have such files elsewhere in the repo. I'd suggest changing the pattern so that it'll scan such files elsewhere as well.

If you agree on the idea, I can create a PR, or you can just update the line to be:
`files: (^|/)(poetry\.lock|Pipfile\.lock|requirements.*\.txt)$`

**Comment by joakimnordling** [comment]
I could add that it might be a bit dangerous to do this change before https://github.com/twu/skjold/issues/114 has been fixed, as the hook won't work properly if it finds multiple files.

**Comment by twu** [comment]
> I could add that it might be a bit dangerous ... as the hook won't work properly if it finds multiple files.

Yes, you are totally right. Iff skjold can handle this properly the expression can also be simplified to `files: (poetry\.lock|Pipfile\.lock|requirements.*\.txt)$` I think. Let's talk in #114 Kiitos! :)
