### ISSUE TITLE
feat: set cache directory via environment variable

### ISSUE THREAD

**Issue by AIGeneratedUsername** [twu/skjold#154]
## What

Allow to define a cache path in any way a user wants: via "pyproject.toml" or via an environment variable.
Environment variable name proposal: `SKJOLD_CACHE_PATH`

It will be required to document which setting takes higher priority during config merging: env config or file config. E.g. Removate uses env variables if both env and file setting were set.

## Why

Simplify CI/CD setup. A developer will not need to modify a `pyproject.toml` file in every repository one by one.

For example, I have dozens of repositories. Every has its own `pyproject.toml` file. Environment variables in CI/CD allow me easily share common cache locations for different tools.

## How other tools do 

If you will take a look at Black, Mypy, Poetry, Renovate, then you will see that all tools allow to set a cache path via an environment variable.

---

**UPDATE**

I found a workaround. I can use `--configuration-file FILE` option with a path to shared file. I share common configuration files across many repositories via a single Git submodule. 
This way I may avoid modifying  "pyproject.toml" files in all repositories.

**Comment by twu** [comment]
👋 Thanks for giving it a shot and reporting an issue :)

Unless I misunderstood your request `skjold` should already support this by setting `SKJOLD_CACHE_DIR` e.g. `SKJOLD_CACHE_DIR=/my/custom/cache/dir skjold ...` or by `export`-ing it in the context you want it to be set in using `export SKJOLD_CACHE_DIR=/my/custom/cache/dir` (See https://github.com/twu/skjold/blob/master/src/skjold/tasks.py#L48-L50) 

Regarding what takes precedence (iff set) I tried to follow https://clig.dev/#guidelines. For anything _configurable_ `skjold` will try to obtain the value for a configuration setting by looking at (highest to lowest):

> via CLI > from ENV > from CONFIGURATION > fallback to DEFAULTS

HTH & let me know if this works for you :)
