### ISSUE TITLE
Running against all sources by default?

### ISSUE THREAD

**Issue by brondsem** [twu/skjold#2]
The readme's Introduction section says this about sources:

> Unless configured explicitly skjold will run the given packages against all of them

However if I run `skjold audit` with a requirements file it says:

> Error: Please specify or configure at least one advisory source.

(by the way, this tool seems great overall.  I'll have a few other issues to report but this tool seems to do what nothing else offers.  Thanks!)

**Comment by twu** [comment]
Good catch! 😅 I'll update the `README` describe the correct usage/initial state.
Thanks for giving this tool a shot and taking the time to report this (and all the other issues)!

Cheers,
Tom
