### ISSUE TITLE
Invalid Specifier on Gemnasium ranges

### ISSUE THREAD

**Issue by pjacobsen-utilimarc** [twu/skjold#235]
In an environment with dbt-core and using the gemnasium database I get the error:

`packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=1.6.0 <1.6.13'`

It appears related to this alert:
https://github.com/advisories/GHSA-p72q-h37j-3hq7

Which makes it into the gemnasium database here

https://gitlab.com/gitlab-org/security-products/gemnasium-db/-/blob/master/pypi/dbt-core/GHSA-p72q-h37j-3hq7.yml

It seems like skjold is expected commas between range specifiers, but gemnasium uses a space

**Comment by twu** [comment]
@pjacobsen-utilimarc Hej Hej! Thanks for taking the time to report and fixing the issue. This is now in [v0.6.2](https://github.com/twu/skjold/releases/tag/v0.6.2). Thanks again :)
