### ISSUE TITLE
click >= 8

### ISSUE THREAD

**Issue by micheller** [twu/skjold#51]
Hi there!

Does skjold really need click version >= 8? 
Looks like it breaks celery with its hardcoded click == 7.1.2. That's celery's problem, of course, but I just wanted to know if 7.1.2 would be fine for skjold too.

**Comment by twu** [comment]
Hej, sorry for the late reply and breaking stuff 😅 If it's still an issue I could try to check whether `skjold` can support both.

The problematic part is https://github.com/twu/skjold/blob/master/src/skjold/tasks.py#L16-L22 where the underlying signature changed from click 7 to 8. This was also the reason for the [v0.3.1](https://github.com/twu/skjold/releases/tag/v0.3.1) right after v0.3.0.

HTH
